version: '3.7'

services:
  postgresql-db:
    image: postgres:13
    environment:
      POSTGRES_DB: pgsql-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - 'pgsql-db:/var/lib/postgresql/data'
    ports:
      - '64036:5432'
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '64057:6379'
volumes:
  pgsql-db:
