version: '3.7'

services:
  notification:
    build:
      context: .
      dockerfile: apps/notification/Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - ./apps/notification/prisma:/app/prisma
    env_file:
      - '.env.example'
    depends_on:
      - postgresql-db
      - redis

  notification-panel:
    build:
      context: .
      dockerfile: apps/notification-panel/Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - '8081:80'
    depends_on:
      - notification

  postgresql-db:
    image: postgres:13
    environment:
      POSTGRES_DB: pgsql-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - 'pgsql-db:/var/lib/postgresql/data'
    ports:
      - '64036:5432'
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '64057:6379'
volumes:
  pgsql-db:
